const initialCats = [
  {
    id: '67rdca3eeb7f6fgeed471815',
    name: 'Пуша',
    breed: 'Дворовая',
    sex: 'Кошка',
    year: 1,
    periodInShelter: 1,
    health: 'good',
    temper: 'dddddddddddddddddddddddd',
    qualities: [
      '67rdca3eeb7f6fgeed471198',
      '67rdca3eeb7f6fgeed471102',
      '67rdca3eeb7f6fgeed471100',
    ],
    history:
      'Она грациозна, степенна и как Снежная Королева, кажется такой недоступной. Хотя, чему тут удивляться. Если жить долгое время на улице, где страшно, холодно и так одиноко, волей не волей, станешь холодной и недоступной. Она грациозна, степенна и как Снежная Королева, кажется такой недоступной. Хотя, чему тут удивляться. Если жить долгое время на улицеОна грациозна, степенна и как Снежная Королева, кажется такой недоступной. Хотя, чему тут удивляться. Если жить долгое время на улице',
  },
  {
    id: '67rdca3eeb7f6fgeed471816',
    name: 'Пуша',
    breed: 'Дворовая',
    sex: 'Кошка',
    year: 1,
    periodInShelter: 1,
    health: 'good',
    temper: 'dddddddddddddddddddddddd',
    qualities: [
      '67rdca3eeb7f6fgeed471198',
      '67rdca3eeb7f6fgeed471102',
      '67rdca3eeb7f6fgeed471100',
    ],
    history:
      'Она грациозна, степенна и как Снежная Королева, кажется такой недоступной. Хотя, чему тут удивляться. Если жить долгое время на улице',
  },
  {
    id: '67rdca3eeb7f6fgeed471817',
    name: 'Пуша',
    breed: 'Дворовая',
    sex: 'Кот',
    year: 3,
    periodInShelter: 1,
    health: 'good',
    temper: 'dddddddddddddddddddddddd',
    qualities: [
      '67rdca3eeb7f6fgeed471198',
      '67rdca3eeb7f6fgeed471102',
      '67rdca3eeb7f6fgeed471100',
    ],
    history:
      'Она грациозна, степенна и как Снежная Королева, кажется такой недоступной. Хотя, чему тут удивляться. Если жить долгое время на улице, где страшно, холодно и так одиноко, волей не волей, станешь холодной и недоступной.',
  },
  {
    id: '67rdca3eeb7f6fgeed471818',
    name: 'Пуша',
    breed: 'Дворовая',
    sex: 'Кот',
    year: 4,
    periodInShelter: 1,
    health: 'good',
    temper: 'dddddddddddddddddddddddd',
    qualities: [
      '67rdca3eeb7f6fgeed471198',
      '67rdca3eeb7f6fgeed471102',
      '67rdca3eeb7f6fgeed471100',
    ],
    history:
      'Она грациозна, степенна и как Снежная Королева, кажется такой недоступной. Хотя, чему тут удивляться. Если жить долгое время на улице, где страшно, холодно и так одиноко, волей не волей, станешь холодной и недоступной.',
  },
  {
    id: '67rdca3eeb7f6fgeed471819',
    name: 'Пуша',
    breed: 'Дворовая',
    sex: 'Кот',
    year: 6,
    periodInShelter: 1,
    health: 'good',
    temper: 'dddddddddddddddddddddddd',
    qualities: [
      '67rdca3eeb7f6fgeed471198',
      '67rdca3eeb7f6fgeed471102',
      '67rdca3eeb7f6fgeed471100',
    ],
    history:
      'Она грациозна, степенна и как Снежная Королева, кажется такой недоступной. Хотя, чему тут удивляться. Если жить долгое время на улице, где страшно, холодно и так одиноко, волей не волей, станешь холодной и недоступной.',
  },
  {
    id: '67rdca3eeb7f6fgeed471820',
    name: 'Пуша',
    breed: 'Дворовая',
    sex: 'Кошка',
    year: 8,
    periodInShelter: 1,
    health: 'good',
    temper: 'dddddddddddddddddddddddd',
    qualities: [
      '67rdca3eeb7f6fgeed471198',
      '67rdca3eeb7f6fgeed471102',
      '67rdca3eeb7f6fgeed471100',
    ],
    history:
      'Она грациозна, степенна и как Снежная Королева, кажется такой недоступной. Хотя, чему тут удивляться. Если жить долгое время на улице, где страшно, холодно и так одиноко, волей не волей, станешь холодной и недоступной.',
  },
  {
    id: '67rdca3eeb7f6fgeed471821',
    name: 'Пуша',
    breed: 'Дворовая',
    sex: 'Кошка',
    year: 12,
    periodInShelter: 1,
    health: 'good',
    temper: 'dddddddddddddddddddddddd',
    qualities: [
      '67rdca3eeb7f6fgeed471198',
      '67rdca3eeb7f6fgeed471102',
      '67rdca3eeb7f6fgeed471100',
    ],
    history:
      'Она грациозна, степенна и как Снежная Королева, кажется такой недоступной. Хотя, чему тут удивляться. Если жить долгое время на улице, где страшно, холодно и так одиноко, волей не волей, станешь холодной и недоступной.',
  },
  {
    id: '67rdca3eeb7f6fgeed471822',
    name: 'Пуша',
    breed: 'Дворовая',
    sex: 'Кот',
    year: 5,
    periodInShelter: 1,
    health: 'good',
    temper: 'dddddddddddddddddddddddd',
    qualities: [
      '67rdca3eeb7f6fgeed471198',
      '67rdca3eeb7f6fgeed471102',
      '67rdca3eeb7f6fgeed471100',
    ],
    history:
      'Она грациозна, степенна и как Снежная Королева, кажется такой недоступной. Хотя, чему тут удивляться. Если жить долгое время на улице, где страшно, холодно и так одиноко, волей не волей, станешь холодной и недоступной.',
  },
  {
    id: '67rdca3eeb7f6fgeed471823',
    name: 'Пуша',
    breed: 'Дворовая',
    sex: 'Кот',
    year: 6,
    periodInShelter: 1,
    health: 'good',
    temper: 'dddddddddddddddddddddddd',
    qualities: [
      '67rdca3eeb7f6fgeed471198',
      '67rdca3eeb7f6fgeed471102',
      '67rdca3eeb7f6fgeed471100',
    ],
    history:
      'Она грациозна, степенна и как Снежная Королева, кажется такой недоступной. Хотя, чему тут удивляться. Если жить долгое время на улице, где страшно, холодно и так одиноко, волей не волей, станешь холодной и недоступной.',
  },
  {
    id: '67rdca3eeb7f6fgeed471824',
    name: 'Пуша',
    breed: 'Дворовая',
    sex: 'Кошка',
    year: 3,
    periodInShelter: 1,
    health: 'good',
    temper: 'dddddddddddddddddddddddd',
    qualities: [
      '67rdca3eeb7f6fgeed471198',
      '67rdca3eeb7f6fgeed471102',
      '67rdca3eeb7f6fgeed471100',
    ],
    history:
      'Она грациозна, степенна и как Снежная Королева, кажется такой недоступной. Хотя, чему тут удивляться. Если жить долгое время на улице, где страшно, холодно и так одиноко, волей не волей, станешь холодной и недоступной.',
  },
  {
    id: '67rdca3eeb7f6fgeed471825',
    name: 'Пуша',
    breed: 'Дворовая',
    sex: 'Кошка',
    year: 4,
    periodInShelter: 1,
    health: 'good',
    temper: 'dddddddddddddddddddddddd',
    qualities: [
      '67rdca3eeb7f6fgeed471198',
      '67rdca3eeb7f6fgeed471102',
      '67rdca3eeb7f6fgeed471100',
    ],
    history:
      'Она грациозна, степенна и как Снежная Королева, кажется такой недоступной. Хотя, чему тут удивляться. Если жить долгое время на улице, где страшно, холодно и так одиноко, волей не волей, станешь холодной и недоступной.',
  },
]

export default initialCats
